### ISSUE TITLE
req.query is possibly undefined

### ISSUE THREAD

**Issue by JasonMan34** [express-validator/express-validator#1045]
So this package overwrites express' own types to declare that req.query is possibly undefined.  
But why? Base express will have an empty object if no query is given, does this package override that behavior?

https://github.com/express-validator/express-validator/blob/f9da949926770f6ca35267973ee6d6823e9c199e/src/base.ts#L9

**Comment by gustavohenke** [comment]
Hey!
That's because at some point I wanted express-validator to be compatible with more than just express, for example restify, that has pretty much the same API.
FWIW, express-validator is 9 years old, whereas the move to not bind libraries together like this is quite younger than that.

Furthermore, if you are not using typescript, you don't have to install `@types/express`.

As for `req.query`... internally we don't care if it's `undefined` or `{}`.

**Comment by JasonMan34** [comment]
I see. Thanks for the response!

If anyone comes across this in the future, I solved my issue by modifying [this middleware from the docs](https://express-validator.github.io/docs/running-imperatively.html) to return a request with the correct type.  
Though this only works if you send `validate` query validators

```ts
type Dict<T = any> = Record<any, T>;

interface Request<T extends Dict> extends ExpressRequest {
  query: T;
}

const validate = <T extends Dict = Dict>(...validations: ValidationChain[]) => {
  return async (req: Request<T>, res: Response, next: NextFunction) => {
    await Promise.all(validations.map(validation => validation.run(req)));

    const errors = validationResult(req);
    if (errors.isEmpty()) {
      return next();
    }

    res.status(400).json({ errors: errors.array() });
  };
};
```

And then I can use it like so:
```ts
interface QueryParams {
  id: number;
  date?: Date;
}

router.get(
  '/active',
  validate<QueryParams>(
    query('id').isNumeric().toInt(),
    query('date').optional().isISO8601().toDate()
  ),
  async (req, res) => {
    const { id, date } = req.query;

    const result = await getUserData(id, date);
    return res.json(result);
  }
);
```
