### ISSUE TITLE
is it safe to access data from request in a dependable field

### ISSUE THREAD

**Issue by jensysantana** [express-validator/express-validator#1053]
[
       check('email').trim()..escape().isEmail().normalizeEmail(),

      check('phone').trim().custom(async function (phone, { req, location, path }) {
              const userData = await UserModel.findOne({ phone, req.body.emial }, 'status fname');
      
              return true;
      });
]
hi, My question is: if  I access email from request like that is not safety?

**Comment by fedeci** [comment]
It is definitely not safe because errors are checked in `validationResult(req)` which is usually run after all the validation chains.
To make your `customValidator` safe you should check `validationResult(req)` both in your custom validator and also after all the validation chains.

Maybe docs needs an update.

**Comment by gustavohenke** [comment]
tbh, there's nothing stopping people from using `matchedData` from within a custom validator - as long as that field's validation has run at that point 🙂
