### ISSUE TITLE
Sanitation and validation order?

### ISSUE THREAD

**Issue by NickWoodward** [express-validator/express-validator#1083]
## Is your feature request related to a problem? Please describe.

So I'm new to express-validator, and just wanted to confirm that `trim()` and `escape` return strings? Because they seem to for me, and led me to fall into the trap of chaining part of my validation like this:

```
router.post('/test', [
    body('example')
        .trim()
        .isString()
], controller.test());
```

it wasn't until I started testing that I noticed it wasn't possible for the above to fail

## Describe the solution you'd like

I might have got this completely wrong, or missed the warning, but if not it might be helpful for the docs on sanitizers to point out that order can matter?

Thanks,

Nick

**Comment by fedeci** [comment]
Sanitizers and validators run in the same order as you add them to the chain. In particular consider that:
1. Values are converted to string before being passed to sanitizers (e.g. `trim()`) and validators from the `validator` lib (the lib on top of which this one is written) 
2. Values are passed as is to custom validators and sanitizers (e.g. `isString()`)

That one, in particular passes because `trim()` mutates the value to a string, so `isString()` is always successful. You can expect a different behaviour swapping them.
