### ISSUE TITLE
Custom validator for array rejects valid input 

### ISSUE THREAD

**Issue by anthonyorona** [express-validator/express-validator#1088]
This is either a bug or I am misusing express-validator. 99% sure I am mis-using the library.

I would like for my array to consist of IDs, MAC addresses, or both. This rule seems like it should do it.

    body('things').isArray({ min: 1}).custom(things => (
      things.every(thing => validator.isInt(thing, {min: 1}) || validator.isMACAddress(thing, {no_separators: false}))
    ))

Expected: 200

Actual: 422
body: [{"value":[1,2,3],"msg":"Expected a string but received a number","param":"things","location":"body"}]

**Comment by fedeci** [comment]
I think you are mixing [validator](https://github.com/validatorjs/validator.js) and express-validator. The latter (this library) is build on top of the former, but they are not meant to be used together easily. Of course you can but you should trick it a little. 
In particular `validator` functions only validate strings, so you should convert the value received from `.custom(value)` to a string before passing it to validator. 
```js
// e.g.
body('things').isArray({ min: 1}).custom(things => (
  things.every(thing => validator.isInt(thing.toString(), {min: 1}) || validator.isMACAddress(thing.toString(), {no_separators: false}))
))
```
Otherwise I suggest you to [imperatively run validators](https://express-validator.github.io/docs/running-imperatively.html), which is also the best and more reliable solution.

**Comment by anthonyorona** [comment]
Thank you, very helpful
