### ISSUE TITLE
Add Validation for Typescript enum matching

### ISSUE THREAD

**Issue by JackCurrie** [express-validator/express-validator#1089]
Hey all, thanks for maintaining this extremely helpful project!

## The Problem

I have a field and I want to enforce that it always matches one of the string values from an enum in my codebase. It would be great if I could do this directly on my router as a validation so that I can be sure that I have a correct value everywhere else that I use this in my codebase.

## Proposed solution
It would look something like the following:

```typescript
enum MyTypes {
  Foo = 'FOO'
  Bar = 'BAR'
}

router.post('/object',
  body('myType').matchesEnum(MyTypes),
  async (req, res) => {

   ...

})


```

**Comment by fedeci** [comment]
Hi @JackCurrie, `enums` are marked as runtime types but `const enums` are not because they are statically replaced at compile time. My concerns are that:
1. It is impossible for us to correctly type a function that only accepts enums as its argument
2. We would add a function that would be only usable in TS

As an alternative to this you may want to convert your enum to an array and use `.isIn(arr)` to validate the param.

**Comment by JackCurrie** [comment]
ok, those points totally make sense. I'm new to the Node and Typescript worlds, so still learning to understand how everything fits together. :)

For now, we just used a custom validation that made a check like the following:

```ts
if (!Object.values(MyEnum).includes(permission)) {
  throw new Error('Not in Enum')
}

```

**Comment by fedeci** [comment]
Just pay attention when using some kind of values line numbers. [example](https://www.typescriptlang.org/play?#code/KYOwrgtgBAglDeBYAUFKAxA9pqBeKA5AEYCGAXgQDQpoBCJATnlAIwAMbKAviigMaYQAZ0wAbYADpRmAOYAKAPJEAVsD4AXCQDcSosMCFyYASmMogA)
