### ISSUE TITLE
How can I enforce that the response body is an exact match???

### ISSUE THREAD

**Issue by anthonyorona** [express-validator/express-validator#1101]
Forgive me for asking such a basic question...but I do not see the answer on Github, nor SO, nor in the docs.

Let's say my API schema accepts request bodies of the exact form:

```
{
    'name': 'Bartleby',
    'description': 'a turtle',
}

```
I want to accept the above, and reject the below:

```
{
    'name': 'Bartleby',
}

{
    'name': 'Bartleby',
    'description': 'a turtle',
    'weight': 200,
}
```

How does one do this?

**Comment by fedeci** [comment]
Closing as I received no answer.

**Comment by erakis** [comment]
@fedeci

I think what @anthonyorona means by `exact match` is that he wants to make sure the schema of the body is exactly this form.

```js
{
    'name': ...
    'description': ...
}
```

So if the body contains other fields than these (`name`, `description`), then it wants to raise an error. 

Ex:

```js
{
    'name': 'Bob'
    'description': 'Card player'
    'age' : 54
}
```

In this case, the validation should fail because the field `age` is not part of the wanted schema.

I too would like to know how to do it ;)

Obviously, it's possible to create a custom task, but it would be a great asset to have this functionality in `express-validator`. Some kind of `matchSchema(true)`?
