### ISSUE TITLE
Does express-validator support all functions provided by validator.js?  '.isISO6391' is not working here

### ISSUE THREAD

**Issue by propertunist** [express-validator/express-validator#1185]
Do I need to do anything special to be able to use all of [the validators](https://github.com/validatorjs/validator.js#sanitizers) provided by validator.js?

I can see that this function to check location codes is listed:  .isISO6391()
However, when I try to use it I see this in the console output: 
> .isISO6391 is not a function

Am I missing something?
Thanks

**Comment by gustavohenke** [comment]
Seems like a miss.
Thanks for finding this one!

**Comment by gustavohenke** [comment]
Well, actually.
Turns out that this validator was only added back in april:
https://github.com/validatorjs/validator.js/pull/1892

And validator hasn't been released since.

[It seems that we have tests to ensure this](https://github.com/express-validator/express-validator/blob/02b69d47659148f71640701bb9c863001239de00/src/chain/validators-impl.spec.ts#L22-L38) 😅 , so I'd be happy to add support for it when its next version is published.

**Comment by propertunist** [comment]
Oh Ok, I see, thanks.
