### ISSUE TITLE
Typescript issue with standard sanitizers

### ISSUE THREAD

**Issue by seand52** [express-validator/express-validator#1221]
Hi,

I'm using the `checkSchema` helper provided by `express-validator` to validate the query for an endpoint. One of the properties in my schema is defined like this

```
const schema =  {
  myProperty: {
    in: 'query' as Location,
    optional: { options: { nullable: true } },
    isBoolean: {
      errorMessage: 'Private must be of type Boolean',
    },
    toBoolean: true,
   }
  },
}
```

The issue I'm having is that when I add the `toBoolean: true` part, I get the following Typescript error when doing `checkSchema(schema)`:

` Type 'boolean' is not assignable to type 'SanitizerSchemaOptions<"toBoolean"> | undefined'`

I had a look at the source code, and there is a type `SanitizerSchemaOptions` defined as:

```
declare type SanitizerSchemaOptions<K extends keyof Sanitizers<any>> = true | {
    options?: Parameters<Sanitizers<any>[K]> | Parameters<Sanitizers<any>[K]>[0];
};
```
So it seems like the value provided to `toBoolean` has to be exactly true, but Typescript is inferring it as a boolean, which doesn't match. If I change my implementation to say `toBoolean: true as true`, then it stops complaining. But doing that is a bit weird. Seeing as this is a very common usecase there must be something I'm missing here but I fail to see what could be the issue from the consumer side. Any thoughts? I can provide the tsConfig if necessary

**Comment by gustavohenke** [comment]
Hey, TS is indeed simplifying the types when you don't specify what you actually want or don't cast the value.
That's why, for example, you had to do this:

```ts
in: 'query' as Location,
```

`'query'` by itself evaluates to `string`, but the type expected by `checkSchema` is the literal value `'query'`.
The same applies to these booleans.

What you can do instead is to type `schema` with the `Schema` type, e.g.

```ts
import { Schema } from 'express-validator';
const schema: Schema = { ... };
```

[Here's a TS playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYwBYFNkGsDKb0gCGANHHhkaQDITKEzAQB2cAvnAGZQQhwDk6AB5go6AM5iAtADdCAG2AATetD4BuALAAobcmZj4Y-ETgBeRNrhwQATwAK3MOlg2AXBa1WrwJu74BHAFdnGz44QjE4GjoGZmJLLwgwWKZ5dyQklLF0uCZAuTlCACM5dHcYKGC2NnjPL2AxACEICFLCXw8vL2duKABZcTFCAHMy-gdgWRh0a0CDOCKZiA44GBsnOGbW9Ha+Wq7Wfa8YCC22jorgo7ZtVk0dLT0mebWnRXICQncPk3MEBNsDiSzjW6QS3g6AWCUFC4Ui0XojCY1zgmSRaUQqOSSOymLyBWKpXKlRm7EO4LgDTOOw6-zqXR60AGEhGYz4EymMxAc3gi1RK1eM2puxR5Ppq1OLXOxKu4NYt3uugw2B+hAAFEYKIQAJT3fAq4zqwXvQ26oA) showing the differences.
