### ISSUE TITLE
Build failed in master branch

### ISSUE THREAD

**Issue by yerycs** [express-validator/express-validator#1274]
## Describe the bug

Build is failed in current master branch

## To Reproduce

Try run `npm run build ` on master branch

## Expected behavior

It should build successfully.

## Current behavior

It throws 4 errors

## Environment:

- Express-validator version: 7.0.1
- Node.js version: 18.19.0

According to my check, latest commit which updates docusaurus version is causing issue.
I tried to fix errors, but I got continuous other issues. 
Can we revert latest commit `22d02112deeb03f6bbe9430d78863a5ff6d8eea3`?
I am going to customize one thing in express-validator and got stuck due to this build issue.

**Comment by yerycs** [comment]
@gustavohenke Could you have a look this issue please?

**Comment by gustavohenke** [comment]
Ha, fun. Seems to happen on a fresh clone. Curiously CI wasn't running the build script, only test one. Updated this in a separate commit.

---

> Current behavior
> It throws 4 errors

This issue was kinda easy to replicate, but in the future please include what those errors are, they might not be obvious.

> Can we revert latest commit

It's best to try fixing the issue forward where possible 👍
