### ISSUE TITLE
Check schema optional options should include optional and checkFalsy

### ISSUE THREAD

**Issue by dawningfuture** [express-validator/express-validator#549]
After extensive searching (and checking the TypeScript types), I can't find how to set the value of the `optional` validator and set `checkFalsy` to true at the same time using the `checkSchema` validation method.

The documentation says that a field's validation can be made optional by including `optional: true` in the `ValidationParamSchema`, but so far as I can tell there isn't a way to set `optional` to `false` and set `checkFalsy` to `true`. My request is to add a key to `ValidatorOptions.OptionalOptions` that allows the user to set whether or not the schema field validation should be optional, and if not optional, to check falsy values.

Here's my setup:

```
// Passed as middleware into route

public static checkSearch: ValidationChain[] = [
        ...checkSchema({
            pageIndex: SearchValidator.pageIndex(),
            pageSize: SearchValidator.pageSize(),
            order: SearchValidator.order(),
            term: SearchValidator.term(true) // true is passed to indicate the field should be optional
        })
    ];
```
```
// Called in checkSchema()

public static term = (isOptional: boolean = false): ValidationParamSchema => {
        return {
            in: 'body',
            errorMessage: 'Term is invalid',
            optional: {
                KEY: isOptional // here I want to be able to set whether or not the field is optional
                checkFalsy: true,
            },
            isLength: {
                errorMessage: 'Term not provided',
                options: {
                    min: 1
                }
            }
        };
    }
```
Thanks for any ideas and help you can offer.

**Comment by gustavohenke** [comment]
Hello @dawningfuture, you _should_ be able to use `optional: { options: { checkFalsy: true } }`, just like you would with regular validators.
Can you check if that works, please?

**Comment by elboletaire** [comment]
It does not work @gustavohenke.

I'm facing this same issue, and I'm not able to get a validation on a non-passed field. I found a way to do it, but it's a dirty trick, and forces me to set both the optional and custom validator fields (thanks to #263...).

This is what my field validation looks like right now:

~~~js
export default checkSchema({
  ...otherCustomDefinitions,
  to: {
    optional: {
      options: {
        checkFalsy: true,
      },
    },
    notEmpty: true,
  },
})
~~~

And here's how I was able to get it working (really dirty though):

~~~js
export default checkSchema({
  ...otherCustomDefinitions,
  to: {
    // required, otherwise the custom validation does not work
    optional: false,
    custom: {
      options: (value) => {
        if (!value) {
          return false
        }
        return true
      },
    },
  },
})
~~~

Other things I've tried without success....

~~~js
export default checkSchema({
  ...otherCustomDefinitions,
  to: {
    optional: false,
    notEmpty: true,
  },
})
~~~

**Comment by gustavohenke** [comment]
What are you looking for exactly, @elboletaire?
I see you want to make your field somehow optional. But it is not clear how.

Please note that `notEmpty` is not a validator on the check API _yet_. It is on the legacy API though.
So, to check that a string has some chars in it, you should use `isEmpty: { negated: true }`.

And to make it optional, know that `optional: true` is telling express-validator to skip validation if the value is `undefined`.
Setting `checkFalsy: true` will also skip validation when the value is any of the falsy ones in JS: `undefined`, `null`, `false`, `0` or `''` (empty string).

I'm closing this issue since we don't seem to have uncovered any bug.

**Comment by elboletaire** [comment]
Sincerely? I'm not sure right now :sweat_smile: 

Everything started because I wanted just one validation to check two fields (I've ended up splitting the logic). Then the issue was just trying to find out the correct combination between `optional` and `isEmpty`, but I think that with what you said I'm able to go forward now.

Thanks!

**Comment by gustavohenke** [comment]
I'm glad I helped!
