### ISSUE TITLE
Why isIn options should be nested array in schema?

### ISSUE THREAD

**Issue by imShara** [express-validator/express-validator#588]
Look at [schema.spec.ts](https://github.com/express-validator/express-validator/blob/ff0cf463fd422dbe6874bbbe68f55a91e23df648/check/schema.spec.ts)

```js
isIn: {
    errorMessage: 'foo',
    negated: true,
    options: [['foo', 'bar']]
}
```

Why need `options: [['foo', 'bar']]` instead `options: ['foo', 'bar']` how it made in original [validator.js](https://github.com/chriso/validator.js)

> **isIn(str, values)** — check if the string is in a array of allowed values.

**Comment by gustavohenke** [comment]
Because `options` should represent all arguments that a validator receives. The best type we have for this in JS? Arrays.

When you only need to pass a single argument, express-validator lets you shortcut this by passing the value directly.
Obviously, if this argument is an array, it conflicts with the multi argument syntax. That's why you have to wrap it in an extra array.

**Comment by imShara** [comment]
But there is only one option - array of allowed values.

Look at isLength function - it's options is object
> *isLength(str [, options])* — options is an object which defaults to {min:0, max: undefined}

matches function wants regexp
> *matches(str, pattern [, modifiers])* — options is pattern

isIn wants only one parameter too, but in express-validator it should be passed through array. So unclear moment.
