### ISSUE TITLE
break validation chain on first error

### ISSUE THREAD

**Issue by kpadu** [express-validator/express-validator#638]
I apologize in advanced if I missed this somewhere in the docs, but say I have the following code:

```javascript
check('foo')
    .exists().withMessage('some message')
    .custom(...)
```
Is there a way that I can prevent `custom` from running if the `exists` check fails?

**Comment by gustavohenke** [comment]
It's not possible yet. #500 implements a basic version of it.

**Comment by BigFax** [comment]
#500 isn't implemented yet. @gustavohenke Do you know when it would be available ? :)

**Comment by pkyeck** [comment]
I have the same problem with sanitizers that I want to run - but only when all validators were successful. Same issue? And what is the status of #751?

**Comment by gustavohenke** [comment]
Hey all! This is out with [v6.2.0](https://github.com/express-validator/express-validator/releases/tag/v6.2.0)! 🚢

**Comment by ItsGosho** [comment]
@gustavohenke Hey,
I saw the two type of chains yesterday and made the idea that I wanted with a body ,so all of the validations can  be at one chain ,like the example in your documentation,but this is like hacking ...
Can  you make something like a one chain ,with multiple validations ,like check(..).custom(...).check(...).custom(...),because i achieved the following with a body and then in custom I get the value ,which is not so bad ,but it can be better :)
BWT the middleware is amazing ,keep it up 👍
