### ISSUE TITLE
presence of pictures in the body

### ISSUE THREAD

**Issue by MegaRoks** [express-validator/express-validator#685]
I check the availability of user-entered data, I check everything except the avatar. Why does not check for a file in the operating system `check ('user_avatar'). Exist (). Not (). IsEmpty ()`?

```js
router.post('/signup', upload.single("user_avatar"), [
    check('user_name').exists().isLength({ min: 4, max: 20 }),
    check('user_email').exists().isEmail().normalizeEmail(),
    check('user_avatar').exists().not().isEmpty(),
    check('user_parole').exists().isLength({ min: 8 }),
    check('about').exists().isLength({ min: 20, max: 220 }),
    check('notifications').exists().not().isEmpty(),
    check('locations').exists().not().isEmpty(),
    check('bookmarks').exists().not().isEmpty()
], (req, res) => {
    try {
        const errors = validationResult(req);
        if (!errors.isEmpty()) {
            return res.status(422).json({
                errors: errors.array()
            });
        }
.....
```

Gives an error message:

```json
{
    "errors": [
        {
            "location": "body",
            "param": "user_avatar",
            "msg": "Invalid value"
        },
        {
            "location": "body",
            "param": "user_avatar",
            "msg": "Invalid value"
        }
    ]
}
```

Why gives an error? I indicated in the postman file.

**Comment by gustavohenke** [comment]
It doesn't work because it seems you are using [multer](https://www.npmjs.com/package/multer), which doesn't treat them as normal body fields in `req.body` (which is correct behaviour IMO).

Since express doesn't officially support file uploads, express-validator doesn't as well (https://github.com/express-validator/express-validator/issues/276#issuecomment-359789000), although you can achieve it with a hacky schema, as demonstrated in that issue.
