### ISSUE TITLE
 invalid email error on certain devices

### ISSUE THREAD

**Issue by Jonofat** [express-validator/express-validator#687]
I am not sure why this is, but I get a validation error on the email address only on certain mobile phones. ("Invalid email address") I tried an old Motorolla with Android 4.something and no issue, yet the issue occurs on Samsung J5 with Android 6. Then it happens on some S8 devices and not others. So, I don't know if I have done something wrong in the code or if it is a bug. This issue does not exists on dektop. 

```
body('email', 'Invalid email address.')
    .normalizeEmail({ gmail_remove_dots: false })
    .isEmail()
    .custom((value, { req }) => {
        return User.findOne({ email: value })
            .then(userDoc => {
                if (userDoc) {
                    return Promise.reject('Email address unavailable.');
                };
            });
    }),
```

**Comment by gustavohenke** [comment]
express-validator takes whatever the client sends and validates as configured (it's a server module).
Since I don't know what the inputs are, I can't pinpoint the configuration issue. 

---

A wild guess: some keyboard apps are sending whitespace chars around the e-mail address. If that's the case, you could try using `.trim()` in your validation chain.

Can you please try debugging this with help of fellow StackOverflow users?
