### ISSUE TITLE
old express-validator function is not working

### ISSUE THREAD

**Issue by syrakozz** [express-validator/express-validator#727]
i update the library to the latest version my code was 
app.use(require("express-validator")());
but it seems like it a breaking change, can you plz tell me the alternative of that line

**Comment by gustavohenke** [comment]
Yup, [it's gone](https://github.com/express-validator/express-validator/releases/tag/v6.0.0).

Since this API hasn't been the main one for a while (1.5 years now), there were no migration guides aimed specifically at it.
Just follow the [Getting started guide](https://express-validator.github.io/docs/) and other guides under the "Features" section and you should be good.
Please let me know if you feel something is not covered well.

**Comment by l2ubin** [comment]
The getting started guide doesnt cover the issue at hand, that is migrating from 5.x to 6. Also putting all the validations and sanitizations at route declarations makes the code unmanagale and unreadable so perhaps an alternative way to the old way of mounting express validator with app.use should be mentioned

**Comment by gustavohenke** [comment]
Hey! Please refer to #735 where an extended chat is happening 🙂
