### ISSUE TITLE
6.0.1 problem when use optional

### ISSUE THREAD

**Issue by t1ma** [express-validator/express-validator#729]
Hi.
I'm not sure but I think it doesn't work correct when use `optional` and then use method like `toInt` always convert `undefined` to `NaN`. I've tried this with `checkSchema` too.
`query('page').optional().isInt().toInt()`

**Comment by gustavohenke** [comment]
Oh, that's weird. I tested it a bit after you reported and I got `null`s only.
Is there something else in your setup?

**Comment by t1ma** [comment]
Only checkSchema and matchedData nothing else.

**Comment by gustavohenke** [comment]
I would like to see an example repo that reproduces the issue then -- it's not looking obvious where the issue is.

**Comment by t1ma** [comment]
Test repository https://github.com/t1ma/test
<img width="403" alt="Screen Shot 2019-07-01 at 9 56 57 AM" src="https://user-images.githubusercontent.com/2250064/60416505-a4bace00-9be6-11e9-9949-596d6a3dcf67.png">

**Comment by blargism** [comment]
I've also noticed this issue with `trim()`.  It creates an empty string when the value is undefined.  Since `undefined !== ""` that can be a problem.

This creates ambiguity when a parameter is optional.  Consider the following:

```javascript
router.get('/thing', [
  check('stuff').optional().trim()
], (req, res) => {
  const data = matchedData(req);
  console.log(data);
});
```

No matter what we send as the `stuff` parameter, we will get either an empty string or the string value.  If we don't send stuff, we still get an empty string within matched data.

That's fine if `stuff` is always there, but we have no way of knowing if the user provided us with an empty string on purpose or if it was just filled in by the library.  We might want to conditionally update a field if it was present in the request and a blank value is an acceptable one.  How do we know if the user was sending us a blank value intentionally or if it was the library inserting a blank value?  I might be mistaken, but it seems like we can't.

If this case is taken care of please help me implement correctly.  If not, this might be a valid bug that needs to be adjusted for more than just ints and strings.

**Comment by welljsjs** [comment]
I am experiencing the similar/at least related problem. I created a very small example repo for that: https://github.com/welljsjs/expressvalidatoroptionaltrimissue

Pass any value to `name` - and it will become an empty string.

**Comment by blargism** [comment]
The following two tests do not pass.  They were run in `src/matched-data.spec.ts`.

```typescript
describe('when option includeOptionals is false', () => {
  it('returns object with optional data', done => {
    const req = {
      headers: { foo: 'bla', bar: '123' },
    };

    const middleware = check(['foo', 'bar', 'baz'])
      .optional()
      .trim()
      .isString();

    middleware(req, {}, () => {
      const data = matchedData(req, { includeOptionals: false });
      expect(data).toHaveProperty('bar', '123');
      expect(data.baz).toBeUndefined();

      done();
    });
  });
});

describe('when option includeOptionals is not set', () => {
  it('returns object with optional data', done => {
    const req = {
      headers: { foo: 'bla', bar: '123' },
    };

    const middleware = check(['foo', 'bar', 'baz'])
      .optional()
      .trim()
      .isString();

    middleware(req, {}, () => {
      const data = matchedData(req);
      expect(data).toHaveProperty('bar', '123');
      expect(data.baz).toBeUndefined();

      done();
    });
  });
});
```

**Comment by gustavohenke** [comment]
Thanks for the help triaging the bug ❤️ A fix is coming really soon!

**Comment by gustavohenke** [comment]
You guys should take a look at v6.1.1. It should fix the problem!

**Comment by t1ma** [comment]
Thanks.
