### ISSUE TITLE
Express validator with babel-node error

### ISSUE THREAD

**Issue by chidimo** [express-validator/express-validator#732]
I am using babel-node to run an express project. Script below

`"dev-start": "nodemon --exec babel-node ./src/bin/www",`

In `app.js` I use express-validator like this

```javascript
import validator from 'express-validator';

app.use(validator());
```

I installed the latest express validator ,6.0.1, and now when I try to start the project the following error is thrown.

The error is not thrown when I downgrade to 5.3.1

![validator](https://user-images.githubusercontent.com/5418113/60270019-72a82400-98e7-11e9-9227-6b707a83f2b2.JPG)

**Comment by gustavohenke** [comment]
It's a breaking change -- [the legacy API](https://express-validator.github.io/docs/5.3.1/legacy-api.html) has been removed. You should migrate to the modern "check APIs", e.g. https://express-validator.github.io/docs/index.html.

There's no official migration guide _yet_ because both styles have coexisted for a few years before its removal.

**Comment by chidimo** [comment]
It seems the solution is to just remove the global middleware in `app.js`. I just tested it on one of my repos, <https://github.com/chidimo/Quick-Credit>. All tests pass.
