### ISSUE TITLE
isBoolean evaluate non-boolean as boolean

### ISSUE THREAD

**Issue by inovramadani** [express-validator/express-validator#904]
Used express-validator version 6.4.0  

I validate as below  
```
body('flag').isBoolean().withMessage('Flag property only accepts boolean')
```

value of flag not only accept boolean, but these value also detected as if valid boolean: "true", "false", ["true"], ["false", "true"]

I worked around it with:  
```
body('flag').custom(flag=> flag=== true || flag=== false).withMessage('Flag property only accepts boolean')
```

**Comment by liqiang372** [comment]
`isBoolean` is original method from [validator library](https://github.com/validatorjs/validator.js/blob/master/src/lib/isBoolean.js#L5). Since the library only validates against string, So it accepts all these formats.

I think it may make sense that api exposed from express-validator can do something like
```js
isBoolean(strict: boolean = false)
```
if `strict` is true, then it only validates the Boolean value

**Comment by inovramadani** [comment]
@liqiang372 thanks for replying. I understood the cause now. But unfortunately, I think what user expects from isBoolean is to evaluate a boolean, not a string or array of strings.  

Does below code only work for typescript?
```
isBoolean(strict: boolean = false)
```

I tried with something like below in javascript but still accepts strings and arrays.
```
body('flag').isBoolean(true).withMessage('Flag property only accepts boolean')
```

**Comment by liqiang372** [comment]
@inovramadani oops, what I mean is we can enhance the api to do that, I'm afraid you have to do the workaround by now.
I'm just imagining the api would be like that in source code. And it will work both for typescript and javascript
