### ISSUE TITLE
Express Array Validator fails when the array size increases 1000

### ISSUE THREAD

**Issue by yogeshkudikala** [express-validator/express-validator#912]
The express validator fails to read and validate elements of array if the array size increases 1000.
We are validating the array elements as follows
```
 body('ids).optional().isArray(),
 body('ids.*').not().isEmpty().withMessage('Required')
    .trim().isAlphanumeric().withMessage('Alpha Numeric')
    .isLength({ min: 1, max: 10 }).withMessage('Max 10 Characters'),

```
Where ids would be an array like ['T0001','T0002','T0003',...,'T1100']. So now this array contains 1100 elements.
But if  we reduce the size of elements to 500 or 600 the above validation works perfectly. Is there a different way to validate array of large size?

**Comment by liqiang372** [comment]
Hi I tried to reproduce it, but didn't get any luck. Following is my code

client
```js

const ids = Array(2000)
  .fill(0)
  .map((_, index) => {
    return 'T' + `${index}`.padStart(4, '0');
  });
axios.post('/demo', {
  ids,
});
```

server
```js
app.post(
  '/demo',
  [
    body('ids')
      .optional()
      .isArray(),
    body('ids.*')
      .not()
      .isEmpty()
      .withMessage('required')
      .trim()
      .isAlphanumeric()
      .withMessage('Alpha Numeric')
      .isLength({ min: 1, max: 10 })
      .withMessage('Max 10 Characters'),
  ],
  (req, res) => {
    const errors = validationResult(req);
    console.log('---- errors', errors);
    res.end('hello world');
  }
);
```

Can you put up a minimal reproducible repo so that it is easier for us to debug?

**Comment by adarshmadrecha** [comment]
IN my project too, I am getting same error. If the array size is large, I get error.

``` js
router.post('/clientsadd', [
  body('d')
    .exists().withMessage('Required')
    .isArray().withMessage('Should be Array'),
  body('d.*.dataid')
    .exists().withMessage('Required')
    .isInt().withMessage('Int only'),
], async (req, res, next) => {

  const vErrors = validationResult(req);
  if (!vErrors.isEmpty()) {
    return res.json({ errors: vErrors.array(), success: false, msg: 'Check Parameters' });
  }
  // Add the clients to database & other stuff
});
```

If the array is large, the express route returns `Check Parameters`.
This is because `vErrors.isEmpty()` is true.

Cannot reproduce on my local machine with 16GB RAM. The Production API server is just 2GB Ram. So, could that be an issue?

**Comment by adarshmadrecha** [comment]
@liqiang372 Thanks for your suggestions. Your direction pointed me in the right direction.

I think I have narrowed down the issue. Ref: [stackoverflow.com/q/19917401](https://stackoverflow.com/q/19917401/4050261)
Ref: https://expressjs.com/en/4x/api.html#express.json

Just be setting `express.json({limit:'3mb'})` fixed the issue which I was facing.
Will be releasing the API in production server on weekend. Will update it here once I also test this in the production server.

**Comment by gustavohenke** [comment]
Thank you @adarshmadrecha! Yes please keep us in the loop 👍

**Comment by adarshmadrecha** [comment]
After adding `express.json({limit:'3mb'})`. This issue is resolved. 

It's been live in production server for 2 days. Used by 5000+Users.
Hence, can say with confidence, this is the reason which is causing the issue. 
@yogeshkudikala Share your thoughts. 

My suggestion to maintainer:
1st Option - Add somewhere in the documentation about this.
2nd Option - Throw express JSON parser error instead of catching the same. `Not an expert in this`, just a suggestion.

**Comment by yogeshkudikala** [comment]
Setting express json config resolved the issue
